/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.63
 * Generated at: 2022-06-17 09:33:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.time.LocalDateTime;
import java.time.chrono.ChronoZonedDateTime;
import java.time.ZonedDateTime;
import java.time.chrono.ChronoLocalDate;
import java.time.chrono.ChronoLocalDateTime;
import org.apache.jasper.tagplugins.jstl.core.ForEach;
import java.time.LocalDate;
import java.util.Locale;
import java.time.format.DateTimeFormatter;
import fr.eni.projetEnchere.bll.ArticleVenduManager;
import fr.eni.projetEnchere.bll.CategorieManager;
import fr.eni.projetEnchere.bo.CategorieArticle;
import fr.eni.projetEnchere.bo.ArticleVendu;
import java.util.List;
import fr.eni.projetEnchere.bo.Utilisateur;

public final class AccueilConnecte_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/jsp/navbar.jsp", Long.valueOf(1655458033706L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("fr.eni.projetEnchere.bo.Utilisateur");
    _jspx_imports_classes.add("java.time.chrono.ChronoLocalDate");
    _jspx_imports_classes.add("fr.eni.projetEnchere.bo.CategorieArticle");
    _jspx_imports_classes.add("java.time.chrono.ChronoLocalDateTime");
    _jspx_imports_classes.add("org.apache.jasper.tagplugins.jstl.core.ForEach");
    _jspx_imports_classes.add("java.time.ZonedDateTime");
    _jspx_imports_classes.add("java.time.LocalDateTime");
    _jspx_imports_classes.add("fr.eni.projetEnchere.bo.ArticleVendu");
    _jspx_imports_classes.add("fr.eni.projetEnchere.bll.CategorieManager");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.time.chrono.ChronoZonedDateTime");
    _jspx_imports_classes.add("java.util.Locale");
    _jspx_imports_classes.add("java.time.LocalDate");
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
    _jspx_imports_classes.add("fr.eni.projetEnchere.bll.ArticleVenduManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link href=\"bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("	type=\"text/css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"styles/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"styles/navbar.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"styles/accueil.css\">\r\n");
      out.write("<script src=\"bootstrap/js/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("<script src=\"bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"bootstrap/js/wow.min.js\"></script>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Accueil quand connecte</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Navbar -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!-- Connected page  -->\r\n");
      out.write("<!-- commit -->\r\n");
      out.write(" 	\r\n");
 if( session.getAttribute("ConnectedUser") != null){ 
      out.write("\r\n");
      out.write(" 		<!--Navbar-->\r\n");
      out.write(" \r\n");
      out.write("    <nav class=\"navbar\">\r\n");
      out.write("      <div class=\"brand-title\"> <a href=\"");
      out.print(request.getContextPath());
      out.write("/AccueilConnecte\"> Eni-Enchères </a></div>\r\n");
      out.write("      \r\n");
      out.write("      <a href=\"#\" class=\"toggle-button\">\r\n");
      out.write("          <span class=\"bar\"></span>\r\n");
      out.write("          <span class=\"bar\"></span>\r\n");
      out.write("          <span class=\"bar\"></span>\r\n");
      out.write("      </a>\r\n");
      out.write("     \r\n");
      out.write("      <div class=\"navbar-links\">\r\n");
      out.write("      ");
Utilisateur connectedUser = (Utilisateur) session.getAttribute("ConnectedUser"); 
      out.write("\r\n");
      out.write("          <ul>\r\n");
      out.write("              <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/AccueilConnecte\">Enchères  <i class=\"fas fa-bullhorn\"></i></a></li>\r\n");
      out.write("              <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/vendre\">Vendre  <i class=\"fas fa-hand-holding-usd\"></i></a></li>\r\n");
      out.write("              <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/profil?pseudo=");
      out.print(connectedUser.getPseudo());
      out.write("\">Mon Profil  <i class=\"fas fa-user-circle\"></i></a></li>\r\n");
      out.write("              <li><a href=\"AccueilPasConnecte\">Deconnexion  <i class=\"fas fa-sign-in-alt\"></i></a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write(" \r\n");
      out.write(" 	");
 } else {  
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("<!-- Deconnected page -->\r\n");
      out.write("\r\n");
      out.write(" <!--Navbar-->\r\n");
      out.write(" \r\n");
      out.write(" <nav class=\"navbar\">\r\n");
      out.write("        <div class=\"brand-title\">Eni-Enchères</div>\r\n");
      out.write("        \r\n");
      out.write("        <a href=\"#\" class=\"toggle-button\">\r\n");
      out.write("            <span class=\"bar\"></span>\r\n");
      out.write("            <span class=\"bar\"></span>\r\n");
      out.write("            <span class=\"bar\"></span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"navbar-links\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/register\"> Créer Un Compte <i class=\"fas fa-sign-in-alt\"></i></a></li>\r\n");
      out.write("                 <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/login\"> Se Connecter  <i class=\"fas fa-sign-in-alt\"></i></a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("    \r\n");
      out.write("       <!--Banner-->\r\n");
      out.write("    <div class=\"header\">\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"search-bar\">\r\n");
      out.write("\r\n");
      out.write("		<select class=\"input\" id=\"categorie\">\r\n");
      out.write("			");

			CategorieManager ctm = new CategorieManager();
			for (CategorieArticle categorie : ctm.selectAllCategories()) {
			
      out.write("\r\n");
      out.write("			<option name=\"categorie\" value=\"");
      out.print(categorie.getNoCategorie());
      out.write('"');
      out.write('>');
      out.print(categorie.getLibelle());
      out.write("</option>\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("		</select>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"search-box\">\r\n");
      out.write("			<input type=\"text\" class=\"search\"\r\n");
      out.write("				placeholder=\"What are we looking for today?\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<button type=\"submit\" class=\"search-btn\">\r\n");
      out.write("			<i class=\"fas fa-search\"></i>\r\n");
      out.write("		</button>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"recherche-sup\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div>\r\n");
      out.write("			<input type=\"radio\" id=\"huey\" name=\"drone\" value=\"huey\" checked>\r\n");
      out.write("			<label for=\"huey\">Achats</label>\r\n");
      out.write("\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><input name=\"Ssdm\" id=\"Ssdm\" type=\"radio\"> <label\r\n");
      out.write("					class=\"ssdm\" for=\"Ssdm\">Enchères ouvertes</label></li>\r\n");
      out.write("\r\n");
      out.write("				<li><input name=\"Ssdm\" id=\"Ssdm\" type=\"radio\"> <label\r\n");
      out.write("					class=\"ssdm\" for=\"Ssdm\">Mes enchères en cours</label></li>\r\n");
      out.write("\r\n");
      out.write("				<li><input name=\"Ssdm\" id=\"Ssdm\" type=\"radio\"> <label\r\n");
      out.write("					class=\"ssdm\" for=\"Ssdm\">Mes enchères remportées</label></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<div>\r\n");
      out.write("		<input type=\"radio\" id=\"huey\" name=\"drone\" value=\"huey\" checked>\r\n");
      out.write("		<label for=\"huey\">Mes Ventes</label>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li><input name=\"Ssdm\" id=\"Ssdm\" type=\"radio\"> <label\r\n");
      out.write("				class=\"ssdm\" for=\"Ssdm\">Mes ventes en cours</label></li>\r\n");
      out.write("\r\n");
      out.write("			<li><input name=\"Ssdm\" id=\"Ssdm\" type=\"radio\"> <label\r\n");
      out.write("				class=\"ssdm\" for=\"Ssdm\">Ventes non débutés</label></li>\r\n");
      out.write("\r\n");
      out.write("			<li><input name=\"Ssdm\" id=\"Ssdm\" type=\"radio\"> <label\r\n");
      out.write("				class=\"ssdm\" for=\"Ssdm\">Ventes terminées</label></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"head\">\r\n");
      out.write("		<h1>Enchères En Cours</h1>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"card-grid\">\r\n");
      out.write("			");

			ArticleVenduManager avm = new ArticleVenduManager();
			List<ArticleVendu> listeArticles = avm.selectAll();
			
      out.write("\r\n");
      out.write("			");

			if (listeArticles.size() != 0) {
			
      out.write("\r\n");
      out.write("			");

			for (ArticleVendu article : listeArticles) {
			
      out.write("\r\n");
      out.write("			<div class=\"card\">\r\n");
      out.write("				<div class=\"card-header\">\r\n");
      out.write("					");

					if (article.getDateFinEncheres().isAfter(LocalDate.now())) {
					
      out.write("\r\n");
      out.write("					<h1>\r\n");
      out.write("						<a\r\n");
      out.write("							href=\"");
      out.print(request.getContextPath());
      out.write("/detailVente?idArticle=");
      out.print(article.getNoArticle());
      out.write('"');
      out.write('>');
      out.print(article.getNomArticle());
      out.write("</a>\r\n");
      out.write("					</h1>\r\n");
      out.write("					");

					} else {
					
      out.write("\r\n");
      out.write("					<h1>\r\n");
      out.write("						<a\r\n");
      out.write("							href=\"");
      out.print(request.getContextPath());
      out.write("/venteRemporte?idArticle=");
      out.print(article.getNoArticle());
      out.write('"');
      out.write('>');
      out.print(article.getNomArticle());
      out.write("</a>\r\n");
      out.write("					</h1>\r\n");
      out.write("					");

					}
					
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"card-img-container\">\r\n");
      out.write("					<img src=\"img/tournevis.jpeg\" alt=\"\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"card-body\">\r\n");
      out.write("					<div class=\"prix\">\r\n");
      out.write("						<i class=\"fas fa-tag\"></i>");
      out.print(article.getMiseAPrix());
      out.write("</div>\r\n");
      out.write("					");

					if (article.getPrixVente() != 0) {
					
      out.write("\r\n");
      out.write("					<div class=\"prix\">\r\n");
      out.write("						<i class=\"fas fa-tag\"></i>");
      out.print(article.getPrixVente());
      out.write("</div>\r\n");
      out.write("					");

					}
					
      out.write("\r\n");
      out.write("					<div class=\"card-date-enchere\">\r\n");
      out.write("						<p>\r\n");
      out.write("							<i class=\"far fa-clock\"></i>");
      out.print(article.getDateDebutEncheres().format(DateTimeFormatter.ofPattern("dd/MM/YYYY", Locale.FRANCE)));
      out.write("</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"vendeur\">\r\n");
      out.write("						<p>\r\n");
      out.write("							<i class=\"fas fa-id-badge\"></i><a\r\n");
      out.write("								href=\"");
      out.print(request.getContextPath());
      out.write("/profil?pseudo=");
      out.print(article.getVendeur().getPseudo());
      out.write('"');
      out.write('>');
      out.print(article.getVendeur().getPseudo());
      out.write("</a>\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("			");

			} else {
			
      out.write("\r\n");
      out.write("			<h1>Aucun article</h1>\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
